package com.vectis.backend.service;

import com.vectis.backend.domain.entity.InvestmentAsset;
import com.vectis.backend.domain.entity.InvestmentAssetType;
import com.vectis.backend.domain.entity.InvestmentMovement;
import com.vectis.backend.domain.entity.InvestmentMovementType;
import com.vectis.backend.domain.entity.InvestmentValuation;
import com.vectis.backend.domain.entity.User;
import com.vectis.backend.repository.InvestmentRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.MathContext;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.temporal.ChronoUnit;
import java.util.Comparator;
import java.util.List;

/**
 * Genera (y revierte) los "tramos" de cierre de mes para las inversiones del usuario.
 *
 * <p>Al cerrar un mes del cashflow, cada inversión recibe un artefacto de cierre con su
 * mecanismo nativo de tramo, sin tocar ninguna fórmula de cálculo compartida:</p>
 * <ul>
 *   <li><b>FCI</b> (Cuenta Remunerada): un {@code REVALUO} con el interés devengado por TNA
 *       desde el último movimiento hasta fin de mes (capitaliza al saldo).</li>
 *   <li><b>FCI_CUOTAPARTES / LETRA / BONO / ON</b> (familia CP): una valuación a fin de mes
 *       con el último precio conocido (fija el borde del tramo; el rendimiento lo deriva la
 *       diferencia de precio entre valuaciones).</li>
 *   <li><b>PLAZO_FIJO</b>: no-op (su rendimiento es continuo y ya se muestra).</li>
 * </ul>
 *
 * <p>Los artefactos se marcan con {@code autoGenerated=true} para poder eliminarlos al
 * reabrir el período. La idempotencia del cierre la controla {@code MonthPeriodService} con
 * un timestamp en {@code MonthPeriod}.</p>
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class InvestmentMonthCloseService {

    private static final MathContext MC = MathContext.DECIMAL128;
    private static final BigDecimal DAYS_PER_YEAR = new BigDecimal("365");
    private static final BigDecimal MIN_INTEREST  = new BigDecimal("0.01");

    private final InvestmentRepository investmentRepository;

    /**
     * Genera el tramo de cierre a fin de mes para cada inversión del usuario.
     */
    @Transactional
    public void materializeForMonth(User user, int year, int month) {
        LocalDate monthEnd = YearMonth.of(year, month).atEndOfMonth();

        List<InvestmentAsset> assets =
                investmentRepository.findAllByUser_IdOrderByCreatedAtAsc(user.getId());

        int generated = 0;
        for (InvestmentAsset asset : assets) {
            boolean created = switch (asset.getType()) {
                case FCI -> materializeFciRevaluo(asset, monthEnd);
                case FCI_CUOTAPARTES, LETRA, BONO, ON -> materializeCpValuation(asset, monthEnd);
                case PLAZO_FIJO -> false; // sin movimientos/valuaciones: rendimiento continuo
            };
            if (created) {
                investmentRepository.save(asset);
                generated++;
            }
        }
        log.info("materializeForMonth: {} tramo(s) de cierre generados para user {} en {}/{}",
                generated, user.getId(), year, month);
    }

    /**
     * Elimina los artefactos de cierre auto-generados cuya fecha cae dentro del mes indicado.
     * Se usa al reabrir un período para volver al estado previo (idempotencia).
     */
    @Transactional
    public void removeForMonth(User user, int year, int month) {
        YearMonth ym = YearMonth.of(year, month);
        LocalDate firstDay = ym.atDay(1);
        LocalDate monthEnd = ym.atEndOfMonth();

        List<InvestmentAsset> assets =
                investmentRepository.findAllByUser_IdOrderByCreatedAtAsc(user.getId());

        int removed = 0;
        for (InvestmentAsset asset : assets) {
            boolean movRemoved = asset.getMovements().removeIf(m ->
                    m.isAutoGenerated() && inRange(m.getMovementDate(), firstDay, monthEnd));
            boolean valRemoved = asset.getValuations().removeIf(v ->
                    v.isAutoGenerated() && inRange(v.getValuationDate(), firstDay, monthEnd));

            if (movRemoved) {
                recalculateFciPrincipal(asset); // los REVALUO removidos descapitalizan el saldo
            }
            if (movRemoved || valRemoved) {
                investmentRepository.save(asset);
                removed++;
            }
        }
        log.info("removeForMonth: artefactos de cierre revertidos en {} inversión(es) para user {} en {}/{}",
                removed, user.getId(), year, month);
    }

    // ── FCI (Cuenta Remunerada) ──────────────────────────────────────────────

    private boolean materializeFciRevaluo(InvestmentAsset asset, LocalDate monthEnd) {
        BigDecimal saldo = fciBalance(asset);
        if (saldo.signum() <= 0) {
            return false;
        }

        LocalDate reference = lastMovementDate(asset, asset.getPurchaseDate());
        long dias = ChronoUnit.DAYS.between(reference, monthEnd);
        if (dias <= 0) {
            return false;
        }

        // interés = saldo × (TNA/100) × (días/365)
        BigDecimal tna = asset.getTna() != null ? asset.getTna() : BigDecimal.ZERO;
        BigDecimal interes = saldo
                .multiply(tna, MC)
                .divide(new BigDecimal("100"), MC)
                .multiply(new BigDecimal(dias), MC)
                .divide(DAYS_PER_YEAR, MC)
                .setScale(2, RoundingMode.HALF_EVEN);

        if (interes.compareTo(MIN_INTEREST) < 0) {
            return false;
        }

        InvestmentMovement revaluo = InvestmentMovement.builder()
                .investmentAsset(asset)
                .movementDate(monthEnd)
                .type(InvestmentMovementType.REVALUO)
                .amount(interes)
                .autoGenerated(true)
                .build();

        asset.getMovements().add(revaluo);
        recalculateFciPrincipal(asset);
        return true;
    }

    /** Saldo vigente de un FCI: SUSCRIPCION + REVALUO − RESCATE. */
    private BigDecimal fciBalance(InvestmentAsset asset) {
        return asset.getMovements().stream()
                .map(m -> switch (m.getType()) {
                    case SUSCRIPCION, REVALUO -> m.getAmount();
                    case RESCATE              -> m.getAmount().negate();
                })
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    /** Recalcula el principal del FCI a partir de sus movimientos (REVALUO capitaliza). */
    private void recalculateFciPrincipal(InvestmentAsset asset) {
        asset.setPrincipal(fciBalance(asset));
    }

    private LocalDate lastMovementDate(InvestmentAsset asset, LocalDate fallback) {
        return asset.getMovements().stream()
                .map(InvestmentMovement::getMovementDate)
                .max(Comparator.naturalOrder())
                .orElse(fallback);
    }

    // ── Familia CP (Cuotapartes / Letra / Bono / ON) ─────────────────────────

    private boolean materializeCpValuation(InvestmentAsset asset, LocalDate monthEnd) {
        // Si ya existe una valuación a fin de mes, el borde del tramo ya está fijado.
        boolean alreadyHasMonthEnd = asset.getValuations().stream()
                .anyMatch(v -> v.getValuationDate().equals(monthEnd));
        if (alreadyHasMonthEnd) {
            return false;
        }

        BigDecimal price = lastKnownPrice(asset, monthEnd);
        if (price == null) {
            return false; // sin precio previo y no es zero-coupon: no se inventa precio
        }

        InvestmentValuation valuation = InvestmentValuation.builder()
                .investmentAsset(asset)
                .valuationDate(monthEnd)
                .pricePerUnit(price)
                .source("SYSTEM")
                .autoGenerated(true)
                .build();

        asset.getValuations().add(valuation);
        return true;
    }

    /**
     * Último precio conocido en o antes de {@code asOf}. Para LETRA sin valuación previa
     * se usa el valor nominal 1 (zero-coupon). Para el resto sin valuación → null (se omite).
     */
    private BigDecimal lastKnownPrice(InvestmentAsset asset, LocalDate asOf) {
        return asset.getValuations().stream()
                .filter(v -> !v.getValuationDate().isAfter(asOf))
                .max(Comparator.comparing(InvestmentValuation::getValuationDate))
                .map(InvestmentValuation::getPricePerUnit)
                .orElseGet(() -> asset.getType() == InvestmentAssetType.LETRA
                        ? BigDecimal.ONE
                        : null);
    }

    private boolean inRange(LocalDate date, LocalDate from, LocalDate to) {
        return !date.isBefore(from) && !date.isAfter(to);
    }
}
