package com.vectis.backend.mapper;

import com.vectis.backend.domain.entity.InvestmentAsset;
import com.vectis.backend.domain.entity.InvestmentAssetType;
import com.vectis.backend.domain.entity.InvestmentMovement;
import com.vectis.backend.domain.entity.InvestmentPayment;
import com.vectis.backend.domain.entity.InvestmentPaymentStatus;
import com.vectis.backend.domain.entity.InvestmentValuation;
import com.vectis.backend.dto.InvestmentMovementResponse;
import com.vectis.backend.dto.InvestmentPaymentResponse;
import com.vectis.backend.dto.InvestmentResponse;
import com.vectis.backend.dto.InvestmentValuationResponse;
import com.vectis.backend.repository.InvestmentPaymentRepository;
import com.vectis.backend.util.InvestmentValuationCalculator;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@RequiredArgsConstructor
public class InvestmentMapper {

    private final InvestmentPaymentRepository investmentPaymentRepository;

    /**
     * Overload de un solo activo (create/update/movement/valuation): resuelve las amortizaciones
     * cobradas con una query puntual por asset. Aceptable acá porque es un único activo — para
     * listados usar {@link #toResponse(InvestmentAsset, List)} con el batch ya resuelto por el
     * caller, para no incurrir en N+1.
     */
    public InvestmentResponse toResponse(InvestmentAsset asset) {
        List<InvestmentPayment> collectedPayments = isBondOrOn(asset.getType())
                ? investmentPaymentRepository.findAllByInvestmentAsset_IdAndStatusOrderByCuttingDateAsc(
                        asset.getId(), InvestmentPaymentStatus.COBRADO)
                : List.of();
        return toResponse(asset, collectedPayments);
    }

    /**
     * Variante batch: el caller (p. ej. {@code InvestmentService#getInvestments}) resuelve los pagos
     * cobrados de TODOS los activos con un único {@code IN()} y agrupa por assetId, evitando N+1.
     * Para tipos que no sean BONO/ON, pasar {@code List.of()} — el campo queda vacío en el response.
     */
    public InvestmentResponse toResponse(InvestmentAsset asset, List<InvestmentPayment> collectedPayments) {
        List<InvestmentMovementResponse> movements = asset.getMovements().stream()
                .map(this::toMovementResponse)
                .toList();

        List<InvestmentValuationResponse> valuations = asset.getValuations().stream()
                .map(this::toValuationResponse)
                .toList();

        List<InvestmentPaymentResponse> collectedAmortizations = collectedPayments.stream()
                .filter(p -> p.getAmortizationPer100() != null && p.getAmortizationPer100().signum() > 0)
                .map(p -> toPaymentResponse(p, asset))
                .toList();

        return InvestmentResponse.builder()
                .id(asset.getId())
                .name(asset.getName())
                .type(asset.getType().name())
                .currency(asset.getCurrency())
                .principal(asset.getPrincipal())
                .currentValue(InvestmentValuationCalculator.calculateCurrentValue(asset))
                .purchaseDate(asset.getPurchaseDate())
                .maturityDate(asset.getMaturityDate())
                .tna(asset.getTna())
                .accountId(asset.getAccount() != null ? asset.getAccount().getId() : null)
                .accountName(asset.getAccount() != null ? asset.getAccount().getName() : null)
                .createdAt(asset.getCreatedAt())
                .updatedAt(asset.getUpdatedAt())
                .autoTrack(asset.isAutoTrack())
                .externalId(asset.getExternalId())
                .movements(movements)
                .valuations(valuations)
                .includeInCashflow(asset.isIncludeInCashflow())
                .status(asset.getStatus().name())
                .collectDate(asset.getCollectDate())
                .paymentAccountId(asset.getPaymentAccount() != null ? asset.getPaymentAccount().getId() : null)
                .paymentAccountName(asset.getPaymentAccount() != null ? asset.getPaymentAccount().getName() : null)
                .paymentCurrency(asset.getPaymentCurrency())
                .collectedAmortizations(collectedAmortizations)
                .build();
    }

    public InvestmentMovementResponse toMovementResponse(InvestmentMovement movement) {
        return new InvestmentMovementResponse(
                movement.getId(),
                movement.getMovementDate(),
                movement.getType().name(),
                movement.getAmount(),
                movement.getUnits(),
                movement.getInterestOverride(),
                movement.isAutoGenerated(),
                movement.getCreatedAt()
        );
    }

    public InvestmentValuationResponse toValuationResponse(InvestmentValuation valuation) {
        return new InvestmentValuationResponse(
                valuation.getId(),
                valuation.getValuationDate(),
                valuation.getPricePerUnit(),
                valuation.getSource(),
                valuation.isAutoGenerated(),
                valuation.getCreatedAt()
        );
    }

    /**
     * El mapper no depende de servicios (mantiene la capa de mapeo aislada), pero el monto estimado
     * de renta/amortización se delega en {@link InvestmentValuationCalculator#estimatePaymentAmounts}
     * — única fuente de verdad compartida con {@code InvestmentPaymentService#toResponse}, para que
     * ambos caminos no diverjan si la fórmula cambia.
     */
    private InvestmentPaymentResponse toPaymentResponse(InvestmentPayment p, InvestmentAsset asset) {
        InvestmentValuationCalculator.EstimatedPaymentAmounts estimated =
                InvestmentValuationCalculator.estimatePaymentAmounts(p, asset);

        return InvestmentPaymentResponse.builder()
                .id(p.getId())
                .cuttingDate(p.getCuttingDate())
                .rentPer100(p.getRentPer100())
                .amortizationPer100(p.getAmortizationPer100())
                .estimatedRentAmount(estimated.rent())
                .estimatedAmortizationAmount(estimated.amortization())
                .currency(p.getCurrency())
                .status(p.getStatus().name())
                .source(p.getSource().name())
                .userEdited(p.isUserEdited())
                .collectedDate(p.getCollectedDate())
                .rentTransactionId(p.getRentTransaction() != null ? p.getRentTransaction().getId() : null)
                .amortizationTransactionId(p.getAmortizationTransaction() != null ? p.getAmortizationTransaction().getId() : null)
                .residualAfterPer100(p.getResidualAfterPer100())
                .build();
    }

    private boolean isBondOrOn(InvestmentAssetType type) {
        return type == InvestmentAssetType.BONO || type == InvestmentAssetType.ON;
    }
}
