package com.vectis.backend.service;

import com.vectis.backend.domain.entity.InvestmentAsset;
import com.vectis.backend.domain.entity.InvestmentAssetType;
import com.vectis.backend.domain.entity.InvestmentMovement;
import com.vectis.backend.domain.entity.InvestmentMovementType;
import com.vectis.backend.domain.entity.InvestmentValuation;
import com.vectis.backend.domain.entity.User;
import com.vectis.backend.repository.InvestmentRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.BDDMockito.given;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

@ExtendWith(MockitoExtension.class)
@DisplayName("InvestmentMonthCloseService")
class InvestmentMonthCloseServiceTest {

    @InjectMocks
    private InvestmentMonthCloseService service;

    @Mock private InvestmentRepository investmentRepository;

    private User user;
    private UUID userId;

    @BeforeEach
    void setUp() {
        userId = UUID.randomUUID();
        user = User.builder()
                .id(userId).email("user@vectis.com")
                .fullName("Test User").passwordHash("hash")
                .build();
    }

    // ── FCI (Cuenta Remunerada) ──────────────────────────────────────────────

    @Test
    @DisplayName("FCI: genera un REVALUO con el interés por TNA del período (capitaliza)")
    void fci_generaRevaluoPorTna() {
        // saldo 1.000.000, TNA 36,5%, 30 días → interés = 1.000.000 × 0,365 × 30/365 = 30.000,00
        InvestmentAsset fci = buildFci(new BigDecimal("36.5000"),
                susc("1000000.0000", LocalDate.of(2026, 5, 1)));
        given(investmentRepository.findAllByUser_IdOrderByCreatedAtAsc(userId))
                .willReturn(List.of(fci));

        service.materializeForMonth(user, 2026, 5);

        verify(investmentRepository).save(fci);
        InvestmentMovement generated = fci.getMovements().stream()
                .filter(InvestmentMovement::isAutoGenerated).findFirst().orElseThrow();
        assertThat(generated.getType()).isEqualTo(InvestmentMovementType.REVALUO);
        assertThat(generated.getMovementDate()).isEqualTo(LocalDate.of(2026, 5, 31));
        assertThat(generated.getAmount()).isEqualByComparingTo("30000.00");
        // capitaliza: principal = 1.000.000 + 30.000
        assertThat(fci.getPrincipal()).isEqualByComparingTo("1030000.00");
    }

    @Test
    @DisplayName("FCI: si no transcurrieron días hasta fin de mes, no genera tramo")
    void fci_sinDias_noGenera() {
        InvestmentAsset fci = buildFci(new BigDecimal("36.5000"),
                susc("1000000.0000", LocalDate.of(2026, 5, 31))); // mismo día que monthEnd
        given(investmentRepository.findAllByUser_IdOrderByCreatedAtAsc(userId))
                .willReturn(List.of(fci));

        service.materializeForMonth(user, 2026, 5);

        verify(investmentRepository, never()).save(any());
        assertThat(fci.getMovements()).noneMatch(InvestmentMovement::isAutoGenerated);
    }

    // ── Familia CP ───────────────────────────────────────────────────────────

    @Test
    @DisplayName("CP: genera una valuación a fin de mes con el último precio conocido")
    void cp_generaValuacionFinDeMes() {
        InvestmentAsset cp = buildCp(InvestmentAssetType.FCI_CUOTAPARTES,
                valuation("1500.0000", LocalDate.of(2026, 5, 15)));
        given(investmentRepository.findAllByUser_IdOrderByCreatedAtAsc(userId))
                .willReturn(List.of(cp));

        service.materializeForMonth(user, 2026, 5);

        verify(investmentRepository).save(cp);
        InvestmentValuation generated = cp.getValuations().stream()
                .filter(InvestmentValuation::isAutoGenerated).findFirst().orElseThrow();
        assertThat(generated.getValuationDate()).isEqualTo(LocalDate.of(2026, 5, 31));
        assertThat(generated.getPricePerUnit()).isEqualByComparingTo("1500.0000");
        assertThat(generated.getSource()).isEqualTo("SYSTEM");
    }

    @Test
    @DisplayName("CP: si ya existe valuación a fin de mes, no genera otra")
    void cp_yaTieneFinDeMes_noGenera() {
        InvestmentAsset cp = buildCp(InvestmentAssetType.LETRA,
                valuation("1020.0000", LocalDate.of(2026, 5, 31)));
        given(investmentRepository.findAllByUser_IdOrderByCreatedAtAsc(userId))
                .willReturn(List.of(cp));

        service.materializeForMonth(user, 2026, 5);

        verify(investmentRepository, never()).save(any());
        assertThat(cp.getValuations()).hasSize(1);
    }

    // ── PLAZO_FIJO ───────────────────────────────────────────────────────────

    @Test
    @DisplayName("PLAZO_FIJO: no genera ningún artefacto")
    void plazoFijo_noGenera() {
        InvestmentAsset pf = InvestmentAsset.builder()
                .id(UUID.randomUUID()).user(user)
                .name("PF").type(InvestmentAssetType.PLAZO_FIJO)
                .currency("ARS").principal(new BigDecimal("500000.0000"))
                .purchaseDate(LocalDate.of(2026, 5, 1)).tna(new BigDecimal("40.0000"))
                .movements(new ArrayList<>()).valuations(new ArrayList<>())
                .build();
        given(investmentRepository.findAllByUser_IdOrderByCreatedAtAsc(userId))
                .willReturn(List.of(pf));

        service.materializeForMonth(user, 2026, 5);

        verify(investmentRepository, never()).save(any());
    }

    // ── removeForMonth ───────────────────────────────────────────────────────

    @Test
    @DisplayName("removeForMonth borra solo los artefactos auto-generados del mes y recalcula el principal")
    void removeForMonth_borraSoloAutoGeneradosYRecalcula() {
        InvestmentMovement userSusc = susc("1000000.0000", LocalDate.of(2026, 5, 1));
        InvestmentMovement autoRevaluo = InvestmentMovement.builder()
                .id(UUID.randomUUID()).type(InvestmentMovementType.REVALUO)
                .amount(new BigDecimal("30000.0000")).movementDate(LocalDate.of(2026, 5, 31))
                .autoGenerated(true).build();

        InvestmentAsset fci = buildFci(new BigDecimal("36.5000"), userSusc);
        fci.getMovements().add(autoRevaluo);
        fci.setPrincipal(new BigDecimal("1030000.0000"));

        given(investmentRepository.findAllByUser_IdOrderByCreatedAtAsc(userId))
                .willReturn(List.of(fci));

        service.removeForMonth(user, 2026, 5);

        verify(investmentRepository).save(fci);
        assertThat(fci.getMovements()).containsExactly(userSusc); // el movimiento del usuario queda
        assertThat(fci.getMovements()).noneMatch(InvestmentMovement::isAutoGenerated);
        assertThat(fci.getPrincipal()).isEqualByComparingTo("1000000.00");
    }

    // ── helpers ──────────────────────────────────────────────────────────────

    private InvestmentAsset buildFci(BigDecimal tna, InvestmentMovement... movements) {
        return InvestmentAsset.builder()
                .id(UUID.randomUUID()).user(user)
                .name("Cuenta Remunerada").type(InvestmentAssetType.FCI)
                .currency("ARS").principal(BigDecimal.ZERO)
                .purchaseDate(LocalDate.of(2026, 5, 1)).tna(tna)
                .movements(new ArrayList<>(List.of(movements)))
                .valuations(new ArrayList<>())
                .build();
    }

    private InvestmentAsset buildCp(InvestmentAssetType type, InvestmentValuation... valuations) {
        return InvestmentAsset.builder()
                .id(UUID.randomUUID()).user(user)
                .name(type.name()).type(type)
                .currency("ARS").principal(new BigDecimal("100000.0000"))
                .purchaseDate(LocalDate.of(2026, 5, 1)).tna(BigDecimal.ZERO)
                .movements(new ArrayList<>())
                .valuations(new ArrayList<>(List.of(valuations)))
                .build();
    }

    private InvestmentMovement susc(String amount, LocalDate date) {
        return InvestmentMovement.builder()
                .id(UUID.randomUUID()).type(InvestmentMovementType.SUSCRIPCION)
                .amount(new BigDecimal(amount)).movementDate(date)
                .autoGenerated(false).build();
    }

    private InvestmentValuation valuation(String price, LocalDate date) {
        return InvestmentValuation.builder()
                .id(UUID.randomUUID()).valuationDate(date)
                .pricePerUnit(new BigDecimal(price)).source("MANUAL")
                .autoGenerated(false).build();
    }
}
