export type InvestmentAssetType = 'FCI' | 'FCI_CUOTAPARTES' | 'PLAZO_FIJO' | 'LETRA' | 'BONO' | 'ON';

export type InvestmentMovementType = 'SUSCRIPCION' | 'RESCATE' | 'REVALUO';

/** Estado del activo: 'COBRADA' una vez liquidado (ver feature de cobro con fecha/split). */
export type InvestmentAssetStatus = 'ACTIVA' | 'COBRADA';

export interface InvestmentMovement {
  id:               string;
  movementDate:     string;   // yyyy-MM-dd
  type:             InvestmentMovementType;
  amount:           number;
  units:            number | null;   // cuotapartes; presente solo en FCI_CUOTAPARTES
  interestOverride?: number | null;  // override manual del interés del tramo (solo FCI; null/ausente = TNA)
  autoGenerated?:   boolean;         // true si se generó al cerrar el mes del cashflow
  createdAt:        string;
}

export interface InvestmentMovementRequest {
  movementDate:  string;
  type:          InvestmentMovementType;
  amount:        number;
  units?:        number;         // requerido para FCI_CUOTAPARTES
  pricePerUnit?: number;         // precio por cuotaparte/nominal al momento del movimiento
}

export interface InvestmentMovementUpdateRequest {
  amount?:           number;          // ajusta el monto del movimiento (tramo REVALUO; capitaliza)
  interestOverride?: number | null;   // override del interés del tramo (SUSC/RESC; no capitaliza). null = restaurar TNA
}

export interface InvestmentValuation {
  id:            string;
  valuationDate: string;
  pricePerUnit:  number;
  source:        'MANUAL' | 'ARGENTINADATOS' | 'DOCTA_CAPITAL' | 'SYSTEM';
  autoGenerated?: boolean;        // true si se generó al cerrar el mes del cashflow
  createdAt:     string;
}

export interface InvestmentValuationRequest {
  valuationDate: string;
  pricePerUnit:  number;
}

export interface InvestmentResponse {
  id:           string;
  name:         string;
  type:         InvestmentAssetType;
  currency:     'ARS' | 'USD';
  principal:    number;       // BigDecimal → number en JSON
  purchaseDate: string;       // yyyy-MM-dd
  maturityDate: string | null;
  tna:          number;       // porcentaje, ej. 65.00
  accountId:    string | null;
  accountName:  string | null;
  autoTrack:    boolean;
  externalId:   string | null;
  includeInCashflow: boolean;
  createdAt:    string;
  updatedAt:    string;
  movements:    InvestmentMovement[];
  valuations:   InvestmentValuation[];
  // Opcionales: el backend siempre los envía; se marcan opcionales acá para no romper
  // fixtures/tests existentes que construyen InvestmentResponse sin ellos. Ausente = 'ACTIVA'.
  status?:      InvestmentAssetStatus;
  collectDate?: string | null;   // yyyy-MM-dd; fecha de cobro elegida por el usuario (null si ACTIVA)
  /** Solo BONO/ON: cuenta de cobro de renta/amortización, si difiere de la cuenta del activo. */
  paymentAccountId?:   string | null;
  paymentAccountName?: string | null;
  /** Solo BONO/ON: moneda en la que se cobran renta/amortización. */
  paymentCurrency?:    'ARS' | 'USD' | null;
  /**
   * Solo BONO/ON: pagos de amortización ya cobrados (status='COBRADO', amortizationPer100>0).
   * El backend los puebla únicamente para estos dos tipos; el resto nunca trae este campo.
   * Se usa para neutralizar el escalón de precio (devolución de capital) en `calcTramosCP` y
   * para el gross-up de `tirAcumuladaCP`.
   */
  collectedAmortizations?: InvestmentPaymentResponse[];
}

export interface InvestmentRequest {
  name:         string;
  type:         InvestmentAssetType;
  currency:     'ARS' | 'USD';
  principal:    number;
  purchaseDate: string;
  maturityDate: string | null;
  tna:          number;
  accountId:    string | null;
  autoTrack:    boolean;
  externalId:   string | null;
  includeInCashflow: boolean;
  /** Solo BONO/ON: cuenta de cobro de renta/amortización, si difiere de `accountId`. */
  paymentAccountId?: string | null;
  /** Solo BONO/ON: moneda en la que se cobran renta/amortización. */
  paymentCurrency?:  'ARS' | 'USD' | null;
}

export interface InvestmentCollectResponse {
  investmentId:      string;
  amount:            number;
  currency:          'ARS' | 'USD';
  transactionCreated: boolean;
  capital:            number;
  rendimiento:        number;
  collectDate:        string;   // yyyy-MM-dd
  status:             string;   // 'COBRADA'
}

/** Desglose capital/rendimiento a una fecha de cobro dada — GET .../collect-preview?date=... */
export interface InvestmentCollectPreviewResponse {
  capital:            number;
  rendimiento:        number;
  total:              number;
  currency:           'ARS' | 'USD';
  // true solo para PLAZO_FIJO/FCI: el usuario puede sobrescribir el rendimiento precalculado.
  editableRendimiento: boolean;
}

/** Body del POST de cobro. `rendimiento` sólo se manda cuando `editableRendimiento` es true. */
export interface InvestmentCollectRequest {
  collectDate:  string;   // yyyy-MM-dd
  rendimiento?: number;
}

export const ASSET_TYPE_LABELS: Record<InvestmentAssetType, string> = {
  FCI:             'Cuenta Remunerada',
  FCI_CUOTAPARTES: 'Fondo Cuotapartes',
  PLAZO_FIJO:      'Plazo fijo',
  LETRA:           'Letra capitalizable',
  BONO:            'Bono soberano',
  ON:              'Obligación Negociable',
};

export interface MarketApiStatus {
  fciSnapshotsTotal: number;
  fciLastSync:       string | null;   // yyyy-MM-dd
  ppiConfigured:     boolean;
  ppiLastSync?:      string | null;   // yyyy-MM-dd
  mepLastUpdate?:    string | null;   // yyyy-MM-dd
  oficialLastUpdate?: string | null;  // yyyy-MM-dd
}

/** Fuente sincronizada por el refresh on-demand de datos de mercado. */
export type MarketRefreshSourceName = 'mep' | 'oficial' | 'fci' | 'ppi';

export type MarketRefreshStatus = 'refreshed' | 'upToDate' | 'failed' | 'notConfigured' | 'alreadyRunning';

export interface MarketRefreshSource {
  source:     MarketRefreshSourceName;
  status:     MarketRefreshStatus;
  lastUpdate: string | null;   // yyyy-MM-dd
}

export interface MarketRefreshResponse {
  sources: MarketRefreshSource[];
}

export interface FciFundOption {
  fondo:     string;
  categoria: string;
  vcp:       number;
  fecha:     string;
}

export interface InstrumentOption {
  ticker:       string;
  nombre:       string;
  tipo:         string;
  lastPrice:    number | null;
  priceDate:    string | null;
  maturityDate: string | null;
  /** Moneda de pago del instrumento según el catálogo (BONO/ON). Ausente = desconocida. */
  currency?:    'ARS' | 'USD' | null;
}

// ── Calendario de pagos (renta/amortización) — BONO / ON ────────────────────────

export type InvestmentPaymentStatus = 'PENDIENTE' | 'COBRADO' | 'OMITIDO';
export type InvestmentPaymentSource = 'PPI' | 'MANUAL';

export interface InvestmentPaymentResponse {
  id:                        string;
  cuttingDate:               string;   // yyyy-MM-dd
  rentPer100:                number;
  amortizationPer100:        number;
  estimatedRentAmount:       number;
  estimatedAmortizationAmount: number;
  currency:                  'ARS' | 'USD';
  status:                    InvestmentPaymentStatus;
  source:                    InvestmentPaymentSource;
  userEdited:                boolean;
  collectedDate:             string | null;
  rentTransactionId:         string | null;
  amortizationTransactionId: string | null;
  residualAfterPer100:       number | null;
}

/** Body de alta manual (`POST /{id}/payments`) — sólo pagos `source: 'MANUAL'`. */
export interface InvestmentPaymentRequest {
  cuttingDate:          string;   // yyyy-MM-dd
  currency:             'ARS' | 'USD';
  rentAmount?:          number;
  amortizationAmount?:  number;
}

/** Body de edición (`PUT /{id}/payments/{paymentId}`) — sólo pagos PENDIENTE. */
export interface InvestmentPaymentUpdateRequest {
  cuttingDate?:         string;
  rentAmount?:          number;
  amortizationAmount?:  number;
}

/** Body de confirmación (`POST /{id}/payments/{paymentId}/confirm`). */
export interface InvestmentPaymentConfirmRequest {
  collectedDate:        string;   // yyyy-MM-dd
  rentAmount:           number;
  amortizationAmount:   number;
}

export interface InvestmentPaymentConfirmResponse {
  payment:             InvestmentPaymentResponse;
  transactionsCreated: number;
  /** true si el activo pasó a COBRADA (residual 0 y sin más pagos PENDIENTE). */
  assetCollected:      boolean;
}

/** Ítem del badge global `GET /investments/payments/pending`. */
export interface InvestmentPendingPayment {
  paymentId:            string;
  assetId:              string;
  assetName:            string;
  cuttingDate:          string;
  currency:             'ARS' | 'USD';
  estimatedRent:        number;
  estimatedAmortization: number;
}

export const PAYMENT_STATUS_LABELS: Record<InvestmentPaymentStatus, string> = {
  PENDIENTE: 'Pendiente',
  COBRADO:   'Cobrado',
  OMITIDO:   'Omitido',
};

export const ASSET_TINTS = [
  'var(--color-primary)',
  'var(--color-primary-fixed-dim)',
  'var(--color-secondary)',
  'var(--color-tertiary)',
];
